"use client";
import { formatDate } from "@/lib/utils/format";
import type { ItineraryItem, PendingItem, Stop, Transport } from "@/types/trip";
import Link from "next/link";
import { useState } from "react";
export function ItineraryView({ stops, days, pending, transports }: { stops: Stop[]; days: ItineraryItem[]; pending: PendingItem[]; transports: Transport[] }) {
  const [view, setView] = useState<"cities"|"days">("cities");
  const grouped = days.reduce<Record<string, ItineraryItem[]>>((all, item) => { const key = item.activity_date || "Sem data"; (all[key] ||= []).push(item); return all; }, {});
  return <><div className="mb-6 grid grid-cols-2 rounded-2xl bg-pale-blue/70 p-1"><button onClick={() => setView("cities")} className={`rounded-xl py-2 text-sm font-semibold ${view === "cities" ? "bg-petrol text-white" : "text-petrol"}`}>Cidades</button><button onClick={() => setView("days")} className={`rounded-xl py-2 text-sm font-semibold ${view === "days" ? "bg-petrol text-white" : "text-petrol"}`}>Dias</button></div>
  {view === "cities" ? <div className="space-y-3">{stops.map((stop) => { const count = pending.filter((item) => item.stop_id === stop.id).length; const transport = transports.find((item) => item.stop_id === stop.id); return <Link key={stop.id} href={`/cidade/${stop.id}`} className="card block p-5"><p className="eyebrow">Parada {stop.sequence ?? ""}</p><h2 className="mt-1 text-xl font-semibold">{stop.city || stop.name || "Cidade pendente"}</h2>{(stop.start_date || stop.end_date) && <p className="mt-2 text-sm text-muted">{formatDate(stop.start_date) || "Data pendente"} — {formatDate(stop.end_date) || "Data pendente"}</p>}<div className="mt-3 flex flex-wrap gap-2">{count > 0 && <span className="rounded-full bg-sand/25 px-3 py-1 text-xs">{count} {count === 1 ? "pendência" : "pendências"}</span>}{transport && <span className="rounded-full bg-pale-blue px-3 py-1 text-xs">Próximo deslocamento definido</span>}</div></Link>; })}{!stops.length && <p className="text-sm text-muted">As cidades ainda não foram adicionadas.</p>}</div> : <div className="space-y-7">{Object.entries(grouped).map(([date, items]) => <section key={date}><h2 className="section-title mb-3">{date === "Sem data" ? date : formatDate(date)}</h2><div className="card divide-y divide-petrol/5 px-5">{items.map((item) => <div key={item.id} className="py-4"><div className="flex items-start justify-between gap-4"><p className="font-medium">{item.title || item.name || "Atividade"}</p>{item.start_time && <time className="text-sm text-muted">{item.start_time.slice(0,5)}</time>}</div><p className="mt-1 text-xs text-muted">{item.schedule_type === "fixed" || item.schedule_type === "anchor" ? "Horário fixo" : "Horário flexível"}</p></div>)}</div></section>)}{!days.length && <p className="text-sm text-muted">O roteiro por dias ainda não possui atividades.</p>}</div>}</>;
}
